### ISSUE TITLE
Deleting items in 1.16.4

### ISSUE THREAD

**Issue by soxsrampage** [SeanOMik/TamableFoxes#35] opened 2021-02-12 19:03 UTC
When holding a shield and shift clicking to try to give them a tool they will delete the tool and hold the shield. You can take the shield back but your tool will be gone

**Comment by SeanOMik** [comment] 2021-02-24 20:25
Just to make sure, the fox was holding the shield and you tried to give it a tool? If that's what you were doing, I don't have any issues with it. What tools are you trying to give the fox?

**Comment by SeanOMik** [comment] 2021-04-04 17:30
I think this issue was caused by the same issue that #37 had which is now fixed.

**Closed as completed** 2021-05-24 05:05 UTC
