### ISSUE TITLE
Could you please take a look at this issue

### ISSUE THREAD

**Issue by xingfujiuhao** [SeanOMik/TamableFoxes#103] opened 2023-07-29 16:02 UTC
[23:53:26 ERROR]: Entity threw exception at world:105.0,104.0,-472.0
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityLiving.co()" because the return value of "net.seanomik.tamablefoxes.versions.version_1_19_2_R1.EntityTamableFox.getOwner()" is null
        at net.seanomik.tamablefoxes.versions.version_1_19_2_R1.EntityTamableFox.a(EntityTamableFox.java:575) ~[[T][驯服狐狸]TamableFoxes_v2.2.9-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1515) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:408) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:334) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:805) ~[purpur-1.19.2.jar:git-Purpur-1759]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2993) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:427) ~[?:?]
        at net.minecraft.world.entity.animal.Fox.tick(Fox.java:603) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1237) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:716) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.19.2.jar:git-Purpur-1759]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:694) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1581) ~[purpur-1.19.2.jar:git-Purpur-1759]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1759]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1759]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1759]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1759]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by xingfujiuhao** [comment] 2023-07-29 16:06
I'm causing you trouble  Hope it can be resolved

**Comment by SeanOMik** [comment] 2023-08-04 03:07
I believe this is a duplicate of #101. Its already been resolved and a release was made on GitHub. I think I forgot to make a release on SpigotHub, so I'll do that now.

If the latest version doesn't fix it, comment here and I'll reopen the issue

**Closed as completed by SeanOMik** 2023-08-04 03:07 UTC
